package com.ozanarik.mvvmmovieapp.utils

enum class MovieLanguage(val language:String) {

    English("en"),
    Russian("ru"),
    Korean("ko"),
    Japanese("jp"),
    Italian("it"),
    Mexican("mx"),
    French("fr"),
    German("de"),
    Australia("au"),
    Aragonese("an"),
    Akan("ak"),
    Azerbaijani("az"),
    Czech("cz"),
    Afrikaans("af"),
    Latin("la"),
    Turkish("tr"),
    Icelandic("is"),
    Thai("th"),
    Kazakh("kk"),
    Indonesian("id"),
    Portuguese("pt"),
    Dutch("nl"),
    Irish("ga"),
    Hungarian("hu"),
    Armenian("hy"),
    Polish("pl"),
    Ukrainian("uk"),
    Persian("fa"),
    Swedish("sv"),
    Tatar("tt"),
    Danish("da"),
    Turkmen("tk"),
    Uzbek("uz"),
    Greek("el"),
    Spanish("es"),
    Bulgarian("bg"),
    Macedonian("mk"),
    Croatian("hr"),
    Belarusian("be"),
    Slovenian("sl"),

}